//! Shared infrastructure - actor framework, services, core coordination, state.

// Re-export shared infra that now lives in the `jinn-common` leaf crate.
pub use jinn_common::{app_info, app_paths, toml_patch};

pub mod actor;

pub mod actor_deps;
pub mod app_state;
#[cfg(test)]
mod app_state_tests;
pub mod bridge;
pub mod bus;
pub mod core;
pub mod frontend_projection;
pub mod process_kill;
pub mod render_ctx;
pub mod request_dump;
pub mod services;
pub mod session_projection;
pub mod slices;
pub mod state;
pub mod system_resource;
pub mod ui_element;
pub mod ui_element_fake;
pub mod ui_registry;

/// Standard UI registry type for the jinn application.
pub type AppUiRegistry = ui_registry::UiRegistry;

/// Register all UI elements from every feature module.
///
/// Called once during application startup. Each feature module that provides
/// UI elements exposes a `register()` function that adds its elements to the registry.
pub fn register_all_ui_elements(registry: &mut AppUiRegistry) {
    crate::feat::ui::chat_log::register(registry);
    crate::feat::provider::register(registry);
    // The chat input box is a slice; composition registers its element
    // (the kernel's registry cannot reference slice crates).
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::expect_used,
        clippy::indexing_slicing,
        clippy::panic,
        clippy::unreachable,
        clippy::string_slice,
        clippy::uninlined_format_args,
        reason = "test code"
    )]
    // Targeted import (not `use super::*`): the glob would pull this module's
    // child module named `core` into scope, shadowing the `core` crate inside
    // macro-expanded paths (`core::time::Duration`, as generated by rstest).
    use super::{AppUiRegistry, register_all_ui_elements};

    #[rstest::rstest]
    #[test]
    fn register_all_ui_elements_populates_registry() {
        // Given an empty registry.
        let mut registry = AppUiRegistry::new();

        // When registering all UI elements.
        register_all_ui_elements(&mut registry);

        // Then the registry is not empty (has at least one element).
        assert!(registry.iter_mut().count() > 0);
    }

    #[rstest::rstest]
    #[test]
    fn provider_register_adds_streaming_indicator() {
        // Given an empty registry.
        let mut registry = AppUiRegistry::new();

        // When registering provider UI elements.
        crate::feat::provider::register(&mut registry);

        // Then exactly 1 element was added (the streaming indicator).
        assert_eq!(
            registry.iter_mut().count(),
            1,
            "provider::register should add the streaming indicator"
        );
    }
}
