[package]
name = "jinn-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true }
clap-verbosity-flag = { workspace = true }
clap_complete = { workspace = true }
error-stack = { workspace = true }
jinn-domain = { path = "../jinn-domain" }
wasmparser = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true }
wherror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
