[package]
name = "jinn-plugin"
version.workspace = true
edition.workspace = true

[dependencies]
jinn-domain = { workspace = true }
mlua = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
wherror = { workspace = true }
error-stack = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }
kanal = { workspace = true }

[lints]
workspace = true
