[package]
name = "jinn-plugin"
version.workspace = true
edition.workspace = true

[dependencies]
# Internal
jinn-domain = { workspace = true }
jinn-core-types = { workspace = true }

# External
mlua = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
kanal = { workspace = true }
futures = { workspace = true }
dashmap = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
error-stack = { workspace = true }
wherror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
parking_lot = { workspace = true }
serde_json = { workspace = true }
jinn-core-types = { workspace = true }
jinn-domain = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
