[package]
name = "jinn-project"
version.workspace = true
edition.workspace = true

[dependencies]
jinn-cwd-msg = { workspace = true }
jinn-domain = { workspace = true, features = ["test-harness"] }
jinn-preferences-config = { workspace = true }
jinn-project-msg = { workspace = true }
jinn-slices = { workspace = true }
jinn-theme = { workspace = true }
ratatui = { workspace = true }
tracing = { workspace = true }
unicode-segmentation = { workspace = true }

[dev-dependencies]
jinn-core-types = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
