[package]
name = "nsslice-chat-input-box"
version = "0.1.0"
edition = "2024"

[dependencies]
nullslop-component-ui = { workspace = true }
nullslop-component = { workspace = true }
nullslop-protocol = { workspace = true }
nullslop-selection-widget = { workspace = true }
ratatui = { workspace = true }
wherror = { workspace = true }
unicode-segmentation = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
