[package]
name = "jinn-workflow"
version.workspace = true
edition.workspace = true

[dependencies]
petgraph = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
tokio-util = { workspace = true }
arc-swap = { workspace = true }
wherror = { workspace = true }
error-stack = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true, features = ["debug", "display", "from"] }
tracing = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "time"] }

[lints]
workspace = true
