[package]
name = "jinn-web-search"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
tracing = { workspace = true }
wherror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, features = ["gzip"] }
url = "2"
scraper = "0.27"
jinn-web-fetch = { workspace = true, features = ["headless-chrome"] }
tokio = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
mockito = { workspace = true }

[lints]
workspace = true
