[package]
name = "jinn-testutil"
version.workspace = true
edition.workspace = true

[dependencies]
ratatui = { workspace = true }
kameo = { workspace = true }
kameo_actors = { workspace = true }
trouper = { workspace = true }
jinn-slices = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
