[package]
name = "jinn-bench"
version.workspace = true
edition.workspace = true

[lib]
name = "jinn_bench"
path = "src/lib.rs"

[dependencies]
jinn-domain = { workspace = true }
jinn-provider = { workspace = true }
tokio = { workspace = true }
csv = { workspace = true }
jiff = { workspace = true }
comfy-table = { workspace = true }
error-stack = { workspace = true }
wherror = { workspace = true }
tracing = { workspace = true }
include_dir = "0.7"
globset = "0.4"

humantime = { workspace = true }
strip-ansi-escapes = { workspace = true }
tempfile = { workspace = true }
unicode-segmentation = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-python = { workspace = true }
kameo = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true
