[package]
name = "jinn-plugin-api"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
jsonschema = { version = "0.49", default-features = false, features = ["resolve-file"] }

[lints]
workspace = true
