[package]
name = "nullslop-domain"
version = "0.1.0"
edition = "2024"

[features]
default = []
which-key = ["ratatui-which-key"]

[dependencies]
# Internal deps
nullslop-component-ui = { workspace = true }
llm = { workspace = true }
nullslop-selection-widget = { workspace = true }
nullslop-protocol-derive = { workspace = true }

# External deps
serde = { workspace = true }
serde_json = { workspace = true }
jiff = { workspace = true }
derive_more = { workspace = true }
ratatui-which-key = { workspace = true, optional = true }
uuid = { workspace = true }
ratatui = { workspace = true }
async-trait = { workspace = true }
wherror = { workspace = true }
error-stack = { workspace = true }
dirs = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
unicode-segmentation = { workspace = true }
throbber-widgets-tui = { workspace = true }
humantime = { workspace = true }
fuzzy-matcher = { workspace = true }
parking_lot = { workspace = true }
kanal = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
tempfile = { workspace = true }

[lints]
workspace = true
