[package]
name = "nsslice-dashboard"
version = "0.1.0"
edition = "2024"

[dependencies]
nullslop-component-ui = { workspace = true }
nullslop-component = { workspace = true }
nsslice-dashboard-protocol = { workspace = true }
nullslop-protocol = { workspace = true }
ratatui = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
