[package]
name = "jinn-theme-msg"
version.workspace = true
edition.workspace = true
[dependencies]
jinn-core-types = { workspace = true }
jinn-slices = { workspace = true }
serde = { workspace = true }
jinn-theme = { workspace = true, features = ["entry"] }
jinn-selection-widget = { workspace = true }
jinn-picker = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
