[package]
name = "nullslop-intent"
version = "0.1.0"
edition = "2024"

[dependencies]
nullslop-protocol = { workspace = true }
nullslop-component = { workspace = true }
nsslice-pinned-panel = { workspace = true }
nsslice-chat-input-box = { workspace = true }
nsslice-dashboard = { workspace = true }
nsslice-picker = { workspace = true }
nsslice-chat-entry-selection = { workspace = true }
wherror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
jiff = { workspace = true }

[lints]
workspace = true
