[package]
name = "jinn-chat-input"
version.workspace = true
edition.workspace = true

[dependencies]
jinn-chat-input-msg = { workspace = true }
jinn-slices = { workspace = true }
jinn-kernel = { workspace = true }
jinn-config = { workspace = true }
jinn-context = { workspace = true }
jinn-context-curation-msg = { workspace = true }
jinn-export-msg = { workspace = true }
jinn-core-types = { workspace = true }
jinn-session-msg = { workspace = true }
jinn-attendant-msg = { workspace = true }
jinn-session-history-msg = { workspace = true }
jinn-session-store-msg = { workspace = true }
jinn-preferences-config = { workspace = true }
error-stack = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ratatui = { workspace = true }
trouper = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
wherror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
