[package]
name = "nullslop-core"
version = "0.1.0"
edition = "2024"

[dependencies]
nullslop-actor = { workspace = true }
nullslop-actor-host = { workspace = true }
nullslop-component = { workspace = true }
nullslop-protocol = { workspace = true }
nullslop-services = { workspace = true }
kanal = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
nullslop-component = { workspace = true }
nullslop-component-ui = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true
